package registry

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"go.clever-cloud.com/terraform-provider/pkg/resources/addon/cellar"
	"go.clever-cloud.com/terraform-provider/pkg/resources/addon/cellar/bucket"
	"go.clever-cloud.com/terraform-provider/pkg/resources/addon/configprovider"
	"go.clever-cloud.com/terraform-provider/pkg/resources/addon/fsbucket"
	"go.clever-cloud.com/terraform-provider/pkg/resources/addon/generic"
	"go.clever-cloud.com/terraform-provider/pkg/resources/addon/keycloak"
	"go.clever-cloud.com/terraform-provider/pkg/resources/addon/materiakv"
	"go.clever-cloud.com/terraform-provider/pkg/resources/addon/matomo"
	"go.clever-cloud.com/terraform-provider/pkg/resources/addon/metabase"
	"go.clever-cloud.com/terraform-provider/pkg/resources/addon/mongodb"
	"go.clever-cloud.com/terraform-provider/pkg/resources/addon/mysql"
	"go.clever-cloud.com/terraform-provider/pkg/resources/addon/otoroshi"
	"go.clever-cloud.com/terraform-provider/pkg/resources/addon/postgresql"
	"go.clever-cloud.com/terraform-provider/pkg/resources/addon/pulsar"
	"go.clever-cloud.com/terraform-provider/pkg/resources/addon/redis"
	"go.clever-cloud.com/terraform-provider/pkg/resources/application/docker"
	"go.clever-cloud.com/terraform-provider/pkg/resources/application/dotnet"
	"go.clever-cloud.com/terraform-provider/pkg/resources/application/frankenphp"
	"go.clever-cloud.com/terraform-provider/pkg/resources/application/golang"
	"go.clever-cloud.com/terraform-provider/pkg/resources/application/java"
	"go.clever-cloud.com/terraform-provider/pkg/resources/application/nodejs"
	"go.clever-cloud.com/terraform-provider/pkg/resources/application/php"
	"go.clever-cloud.com/terraform-provider/pkg/resources/application/play2"
	"go.clever-cloud.com/terraform-provider/pkg/resources/application/python"
	"go.clever-cloud.com/terraform-provider/pkg/resources/application/ruby"
	"go.clever-cloud.com/terraform-provider/pkg/resources/application/rust"
	"go.clever-cloud.com/terraform-provider/pkg/resources/application/scala"
	"go.clever-cloud.com/terraform-provider/pkg/resources/application/static"
	"go.clever-cloud.com/terraform-provider/pkg/resources/application/v"
	"go.clever-cloud.com/terraform-provider/pkg/resources/drain"
	"go.clever-cloud.com/terraform-provider/pkg/resources/networkgroup"
)

var Datasources = []func() datasource.DataSource{}

var Resources = []func() resource.Resource{
	generic.NewResourceAddon,
	bucket.NewResourceCellarBucket,
	cellar.NewResourceCellar,
	fsbucket.NewResourceFSBucket,
	java.NewResourceJava("war"),
	materiakv.NewResourceMateriaKV,
	metabase.NewResourceMetabase,
	mongodb.NewResourceMongoDB,
	mysql.NewResourceMySQL,
	nodejs.NewResourceNodeJS,
	otoroshi.NewResourceOtoroshi,
	php.NewResourcePHP,
	postgresql.NewResourcePostgreSQL,
	python.NewResourcePython,
	ruby.NewResourceRuby,
	scala.NewResourceScala(),
	static.NewResourceStatic(),
	docker.NewResourceDocker,
	drain.NewDatadogDrain,
	drain.NewNewRelicDrain,
	drain.NewElasticsearchDrain,
	drain.NewSyslogUDPDrain,
	drain.NewSyslogTCPDrain,
	drain.NewHTTPDrain,
	drain.NewOVHDrain,
	keycloak.NewResourceKeycloak,
	redis.NewResourceRedis,
	golang.NewResourceGo,
	frankenphp.NewResourceFrankenPHP,
	play2.NewResourcePlay2(),
	pulsar.NewResourcePulsar,
	rust.NewResourceRust,
	networkgroup.NewResourceNetworkgroup,
	v.NewResourceV,
	matomo.NewResourceMatomo,
	configprovider.NewResourceConfigProvider,
	dotnet.NewResourceDotnet,
}
