name: Git Checks

on:
  - pull_request

jobs:
  block-fixup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Block Fixup Commits
      uses: 13rac1/block-fixup-merge-action@v2.0.0
  conventional-commit:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webiny/action-conventional-commits@v1.3.0

